package by.javaTr.financeAccounting.controller.command;

public enum CommandName {

    ADD_BILL,
    ADMIN_REGISTRATION,
    ADMIN_SIGN_IN,
    ADMIN_SIGN_OUT,
    BILLS_FIND_BY_CATEGORY,
    BILLS_FIND_BY_NAME,
    BILLS_SORT_BY_BALANCE,
    BILLS_SORT_BY_CATEGORY,
    BILLS_SORT_BY_DATE,
    BILLS_SORT_BY_NAME,
    DELETE_ADMIN,
    DELETE_USER,
    GET_BILLS_FOR_MONTH,
    GET_BILLS_FOR_PERIOD,
    PRINT_ADMIN_LIST,
    PRINT_USERS_LIST,
    USER_REGISTRATIONS,
    USER_SIGN_IN,
    USER_SIGN_OUT,
    WRONG_REQUEST,

}
